### ISSUE TITLE
forager/cornchopper pipe adjustment

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#54]
It seems the forager  works a bit better at the end turnaround if I set the pipe to -1.  I am using a ZIP file from Feb. 1. 2013. Tractor: Deutz M620 Forager: Krone 550.  I noticed that the following would happen when set to auto pipe:  When both cornchopper and forager are both turned around and doing their final line up dance, the forager sudden surges forward.  It goes a little too far so the cornchopper stops spraying but the forager is now in "Combi is telling me to stop" mode.

Thanks for all the updates. Other than this small item, the forager/cornchopper are working fine together.  Did all of field 7 with no problems using 2 foragers and 1 Big x.

![stuck](https://f.cloud.github.com/assets/3346683/120826/be99919e-6d3f-11e2-86b9-27f6bee181d2.png)

**Comment by JakobTischler** [comment]
So, we've determined this is actually more a chopper problems than a tractor problem. Remember that at the beginning of a line, the chopper kinda "jumps" a couple of times. Meanwhile, the tractor tries to match the chopper's speed, thus kinda jumping as well. Sometimes that's a bit too far, the the collisions ... collide :)

There's been rumors that the chopper jumping should be fixed with patch v1.4, so we're gonna wait until then, kinda hoping this issue will resolve itself. If it won't, feel free to reopen this issue.
