### ISSUE TITLE
mystical lines with opened HUD

### ISSUE THREAD

**Issue by Brzzl** [netjungle/courseplay#58]
hi all!
detected two lines when the HUD is opened.... one at the right side just below the fruit-sign f. e. when you  have a seeder attached and the other across nearly in the middle of the screen (see attached screenshot).

have experimented with the resolution and recognized that the line across the screen disappears at different resolutions and graphic settings.

greetz
![fsScreen_2013_02_02_08_00_00](https://f.cloud.github.com/assets/3459971/121393/9867fcd4-6d91-11e2-816e-26e0896bfd2d.png)

![fsScreen_2013_02_02_19_53_16](https://f.cloud.github.com/assets/3459971/121395/b91775ea-6d91-11e2-9a46-cc7b8b5b6d99.png)

**Comment by Satissis** [comment]
Yeah I have those as well.
It's lines that have not be totally cleared in the hud image, so the right side shows a small line and in the top there is a line as well. The top line is really hard to see since it's almost transparent.
It should be an easy fix by opening the hud image and clear 10 pixels on the right side and 10 pixels at the top.

**Comment by JakobTischler** [comment]
...or so you would think. I've done that a couple of times now. On my setup, I can almost certainly say I don't have any lines, but since you guys obviously use the same .dds as I do, since it's in the zip, it doesn't really make any sense that some should see them and some shouldn't.

At first I thought it could be a problem with nVidia Photoshop dds plugin. DXT is known to create artefacts, although none where the original source graphic was 100% transparent anyway. But since I've also edited the file with paint.net since, I can't really blame it on either of those two. Or both. 

My newest guess is: it depends on the user's screen resolution. The hud file is 512px by 512px in dimensions, with an ingame width set to 0.2667 (512/1920) and height set to 0.474 (512/1080). Meaning, I've created those dimensions based on a 16:9 resolution. On a 4:3 (say 1024 by 768) resolution, the rendered ingame width and height would be 273.0667px and 364.088px, respectively. Since there is no sub-pixel rendering with the Giants engine, those non-natural numbers could maybe cause some, let's call it disturbance in the force. Or artefacts, if you will. Although, as mentioned before, artefacts are usually a result of certain colors in pixel regions which are not 100% transparent.

Keep in mind, this is just a theory.

**Comment by Satissis** [comment]
Hmm I have studied it a bit.
The dds image is fine when I open it with photoshop.

Then it hits me, the line on the right side is actually a part of the left side top icon and the top part is the bottom part.
There overlay system might have an glitch there from Giants side, where it tiles the image in the overlay and the offset is wrong.
Yes the aspect ratio might also have something to say in this since I'm running 16:10 aspect ratio and in 1920*1200.
I have a theory on how this could be solved.
Move the visible a bit in from both left and bottom side and then use the setOverlayUVs function to set the cordinates on what part of the overlay that needs to be shown.
The setOverlayUVs is listed on http://gdn.giants-software.com/documentation_scripting.php#runtime_function_reference_overlays

The aspect ratio could also be calculated from the hight and with in the game.xml file, so it would be dynamic based on what the user's screen resolution is.

Well this is just a suggestion :)

Kind regards
Satis

**Comment by JakobTischler** [comment]
@Satissis, thanks for analysis. I could indeed confirm it's 1) a resolution problem (4:3 / 16:10 vs 16:9) and 2) the leftovers/"moveovers" from the left and bottom sides.

I tried cutting the image via overlay UVs without touching the dds file itself, to no avail. So as you suggested, I will have to move non-transparent part of the image itself and set new coordinates (in order to have some whitespace on the left/bottom). Theoretically, specific overlay UVs shouldn't even be needed then anymore.
