### ISSUE TITLE
game crash if endpoint is reached (transport mod)

### ISSUE THREAD

**Issue by TobiTo83** [netjungle/courseplay#61]
Post in german here: http://forum.farming-simulator.com/viewtopic.php?f=769&t=51291&p=418176&sid=f6d0339199167aa553a0a3ea9aacf6c1#p418176

the game crashes if the endpoint of transport route is reached. i saw that the tractor was still driving straight ahead after endpoint was reached. i used a small JohnDere 6610v3.4 and the big "Schwader" from original game.

**Comment by JakobTischler** [comment]
Those log errors appear to be caused by two different problems. First off - can you still reproduce the error? Your post was dated January 14th, and we added and changed a lot since then.

2) when the `triggers.lua(66) : attempt to call method 'getCurrentFruitType' (a nil value)` appeared, what trailer were you using, and what was its filltype?

3) When you used the rake, what exactly were you doing? Field work mode? If so, did you have two wait points?

**Comment by JakobTischler** [comment]
Since there hasn't been an answer for 10 days, I will assume the problem is gone. Closed.
