### ISSUE TITLE
Problems using Pöttinger MEX 6

### ISSUE THREAD

**Issue by mastermannrw** [netjungle/courseplay#63]
If I use the Pöttinger MEX 6, this drive yourself and hire a helper for the transport, the following problem occurs:
I set up everything, pick from the combine of Pöttinger MEX 6, assigned to manually set, set it to the helper and then can no longer operate the game.
It is not possible to move the vehicle, either with the controller or with the keyboard.
This condition will change when I dismiss the helper again. After that, everything works perfectly again.
I have already tried several trailers, different tractors but the effect remains the same.

Deutsch:
Wenn ich den Pöttinger MEX 6 benutze, diesen selber fahre und einen Helfer für den Transport einstelle, tritt folgendes Problem auf:
Ich stelle alles ein, wähle den Mähdrescher von Pöttinger MEX 6 aus, setze auf manuell zugewiesen, stelle den Helfer ein und dann lässt sich das Spiel nicht mehr bedienen.
Es ist nicht möglich, das Fahrzeug zu wechseln, weder mit  Kontroller noch mit der Tastatur.
Dieser Zustand ändert sich , wenn ich den Helfer wieder entlasse. Danach funktioniert alles wieder einwandfrei.
Ich habe bereits mehrere Anhänger probiert, verschiedenen Traktoren aber der Effekt bleibt der selbe.

**Comment by JakobTischler** [comment]
Since the Mex is an attachable and not a combine, it operates differently than the regular combines or choppers. But since there is no documentation, for now we have no idea what its functions etc. are. Basically every tool (attachable/implement) that has combine-like functions but is not steerable or motorized is a big unknown for us. 

Actually I wonder why or how CP recognizes the Mex as a combine. In CP-terms, a combine should a) be a vehicle, and b) have a grainTankCapacity of 0 or higher. Both of which the Mex clearly isn't/doesn't have.
