### ISSUE TITLE
Manual in english ? or more tutorial ?

### ISSUE THREAD

**Issue by gui7545** [netjungle/courseplay#71]
Hello,
During the translation of the ModDesc, I realize that I know just I little part of the courseplay.
I used courseplay for 2 years and I find it is a powerful tool but the manual is in german and my german is not as good as my english.
it is pity that they are not more tutorial or video explaining how use it or improve the current wiki.
For example the mode 4 and 6 are not easy to use the first time (I don't know how it work)
have a nice evening
gui

**Comment by Satissis** [comment]
Hmmm that's not totally true :)
I have a video section on youtube with tutorials on CP. Right now it's on 11 tutorials and it will still grow since I have more tutorial comming :)
Here is the link for the playlist:
http://www.youtube.com/playlist?list=PLK52WHo1CM4EHCrFQYS6SL47RgqQBu3xE&feature=view_all

Kind regards
Satis

**Comment by JakobTischler** [comment]
Just a heads up, I'm working on a semi-complete rewrite of the manual, including an English section.

**Comment by gui7545** [comment]
it is already better with the video. If the author agree, you can put it in the wiki
