### ISSUE TITLE
Courseplay issue - game controls freeze

### ISSUE THREAD

**Issue by tbone121974** [netjungle/courseplay#79]
Hi There

I managed to download and install courseplay successfully into FS2013 using the guid Satis put together. It has been working fine for quite a while but recently I'll play the game for about 10-15 mins or so and the controls will not respond. This is on the keyboard/mouse controls and the 360 pad.  I have tried Ctrl + 7 to abort courseplay actions but this doesn' t work.

I've reinstalled the game on steam and used a fresh install of the mod but still have the same problem.

At the end of the logfile I get the following error:

D:/MEDIA/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(110) : attempt to compare number with nil
Error: LUA running function 'update'

Courseplay is the only mod I am running at the moment.

Can anyone help fix this particular issue?

Thanks

**Comment by ThomasGaertner** [comment]
What did U do in this moment when the game froze ?
I suppose something in fieldwork mode, but what und with which equipment???

**Comment by tbone121974** [comment]
the game doesn't freeze. its the controls that become unresponsive. This can happen when I'm driving a vehicle manually or with a vehicle driving a course.

**Comment by tbone121974** [comment]
When the controls do become unresponsive I've had no choice but to exit the game.

**Comment by tbone121974** [comment]
I'm not using any other mods on the game - only courseplay is present.

**Comment by ThomasGaertner** [comment]
What execty did U do in this moment??

**Comment by tbone121974** [comment]
well I tried pressing various keys to regain control.  I couldn't do anything with any of the keyboard or mouse controls to control vehicles within the game.  Neither could I use any of the controls on a 360 pad.  The only thing that worked was to press ALT + TAB to exit the window and exit the game.  Escape didn't work either so I wasn't able to save my progress.  Interestingly when I deleted all my courses and re-recorded them - courseplay seemed to work ok, but then it had the same issue a few hours later.  I'm not sure if it has something to do with the number of routes recorded.  the strange thing is that it stopped working on a route that worked previously.
the error I have this time is:

D:/MEDIA/Documents/My Games/FarmingSimulator2013/mods/ZZZ_courseplay/drive.lua(215) : attempt to compare number with nil
Error: LUA running function 'update'

**Comment by wevee** [comment]
You need to give them more information about what was actually happening when you lost control.  The game doesn't look like its frozen, but it is, because it is writing to the log file.

They need you to give them a verbal picture of what was happening so they might recreate it.  What kind of course were you driving, what mode (combi, target etc)  Did the tractor get into traffic?  Can you recreate it?  If you can, what happens right before it freezes?

In the options, try setting the debug setting to 1, which will add more information to the log file that they can use.

Sorry to step in, but I don't believe you guys are speaking the same language in more then one way.
