### ISSUE TITLE
Combi mode behavior

### ISSUE THREAD

**Issue by wevee** [netjungle/courseplay#84]
Hi again guys, I wanted to bring up two things.  one might be a bug, the other is a slight annoyance.

First the possible bug:  Time frame since the last 2-3 updates, prior to Feb 19, a tipper-tractor in combi mode, If the harvester is moving, it will attempt to match speed and slightly above to move along side which seems normal to begin the emptying.  When the harvester stops at the edge of a field, the tipper-tractor slows to 2 mph as it attempts to move to the side.  It almost seems like the same speed matching, but slightly above to get into position.  If I were to tap forwards or backwards on the harvester and not actually move, the tipper-tractor immediately speeds up to get into position.

the annoyance:  when the harvester is being controlled by a helper, the tipper-tractor has its combi settings set to 50% to empty the harvester.  the tractor won't actually begin to move until the first turn by the harvester after 50%  On larger fields, this could be near to 70-80% and full by the time the tipper gets into position to empty.  Was this intentional, to keep from stopping the harvester at the ends of fields?

**Comment by JakobTischler** [comment]
I can answer you the annoyance part of you question (the bug, Thomas will have to look into that).

You should see the set percentage as a "minimum". "if it's okay for me to unload the combine, _and_ its fill level is under n%, it's go time". _If_ you have "pathfinding" activated, the driver will not drive to unload the combine if the pipe is on the fruit side. Even if the combine's fill level is above the set percentage. If "pathfinding" is deactivated, the driver should go as soon as the combine's fill level reaches the set percentage.

The combine waiting at the end of the line actually isn't a feature by us, it's a game internal method.

So to answer your question: yes, this is fully intentional.

**Comment by wevee** [comment]
Okay, I learned something new, thank you very much for the information.

**Comment by JakobTischler** [comment]
I order to understand better: the problem you state is that the tractor starts its turn maneuver _after_ unloading the combine, but does so with 2mph? Or is it that its driving _to_ the combine with 2mph?

The latter would be correct and intentional in certain situations, the former is rather weird, I even wanna say impossible  - but I know that's a dangerous term to use ;)

The moment the combine is unloaded, the tractor should start its turning maneuver (at least in seven out of eight possible cases) with field speed.

**Comment by wevee** [comment]
While driving to the combine, while in the "drive beside the harvester" state but just before "combine is telling me to stop".  If it is intentional, then I would have to say sorry for taking up your time and have a nice day  :)

**Comment by JakobTischler** [comment]
Okay, so the 2mph during the "drive beside the harvester" state is indeed intentional. Not in all situations, but in the one you describe (combine is stopped/waiting) it is. This is done in order to make sure the driver doesn't arrive too fast and overshoot his unloading point.

**Comment by Voidheartd** [comment]
The annoying thing to me in the process is the "drive behind combine" part. The tractor always goes so slowly during this that it ends up not reaching unload position until the combine is near the end of a row (especially if I change the combine speed with eslimiter), which means more time sitting at the end of rows unloading versus unloading on the move.  Is there some way I could modify it in my local version to be a little faster?

Also is there some where for discussion of courseplay?

**Comment by JakobTischler** [comment]
During the "drive behind combine" state the tractor should use regular field speed. Try increasing it. It is the "drive beside the combine" state where the tractor should go ca. 2 mph - but only if the combine is standing still and waiting. If it's still moving/threshing, a higher speed is used until it reaches the pipe (combine speed plus ca. 1 mph).

> Also is there some where for discussion of courseplay?

For now, no. At least not in English. But I think for bugs et al. this issue tracker should suffice.

**Comment by Voidheartd** [comment]
Well then there's something going wrong because it isn't going at field speed.

**Comment by Voidheartd** [comment]
To be specific, it's when the tractor is considered to be turning that it goes very slow. It's only going 8mph at those times compared to a max of 18 otherwise (max speed is about 23, cp speed settings are all set higher than that).

**Comment by webagencys** [comment]
There is any way to use manure sprayer in Courseplay  to spray manure

**Comment by JakobTischler** [comment]
@Voidheartd 

> To be specific, it's when the tractor is considered to be turning that it goes very slow. It's only going 8mph at those times compared to a max of 18 otherwise (max speed is about 23, cp speed settings are all set higher than that).

Wait, but you said it was going 2 mph, not 8... I mean, the turning speed (which you set in the hud) should be around 7 or 8 mph, so I don't really see the problem with that.

@webagencys 
Yes, just like any other fertilizer tool oder liquid manure barrel.

**Comment by Voidheartd** [comment]
Wevee was talking about 2mph, and that was in reference to moving up beside the combine at the edge of fields. I'm also not a fan of that speed, which is why the turn speed being only 8 mph is annoying.
 It is not going by the setting as I have it set far higher than 8. This means the tractor has a hard time catching up before the combine reaches the edge of the field and you get into the 2mph slow situation, which makes harvesting a slower process over all. This is with using the Buehrer 6135 but I will be switching my haulers to faster tractors shortly and will see how it goes then.

**Comment by JakobTischler** [comment]
Okay, let me clarify how/when/what stuff happens:
1. "drive behind combine" - field speed (set in hud)
2. "drive to combine" - tractor is behind combine and starts approaching - field speed (set in hud)
3. "drive next to combine" - depending on distance to combine: combine speed +/- 2

So please check if a) your combine isn't driving too fast, and b) your field speed is high enough.

**Comment by webagencys** [comment]
Any Way to Refill Solid Manure in Trailer using courseplay for spray manure in farm

**Comment by JakobTischler** [comment]
@webagencys: please create an issue if you have questions. If you don't know the basics of CP, I would implore you not to use the developer's version.

**Comment by Voidheartd** [comment]
So after having switched to a faster tractor, I can see that it is often still turning at 8MPH, despite turn speed being set to like 30mph. The tractor often doesn't get down that far due to being faster but it will end up there if turning long enough.
